on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Build
jobs:
  analyze:
    name: Analyze and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
      - run: flutter pub get
      
  # build_android:
  #   name: Build Android Release
  #   needs: analyze
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: flutter pub get
      - run: flutter build apk --release --split-per-abi
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
        
  # build_ios:
  #   name: Build IOS Release
  #   needs: analyze
  #   runs-on: macos-latest
  #   steps:
  #     - run: flutter pub get
  #     - run: flutter build ios --release --no-codesign
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: release-ios
  #         path: build/ios/iphoneos/Runner.app
